### ISSUE TITLE
Not working in python3 

### ISSUE THREAD

**Issue by mohitmaharana** [ewenchou/bluetooth-proximity#9]
Traceback (most recent call last):
  File "lnsm.py", line 1, in <module>
    from bt_proximity import BluetoothRSSI
  File "/usr/local/lib/python3.5/dist-packages/bt_proximity-0.1-py3.5.egg/bt_proximity/__init__.py", line 1, in <module>
    from bt_rssi import BluetoothRSSI
ImportError: No module named 'bt_rssi'

**Comment by xiaoyu830411** [comment]
I have same issue.

**Comment by ewenchou** [comment]
Looks like duplicate of Issue #7
